//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog_Level_WPF_Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Catalog_Level_WPFContainer : DbContext
    {
        //static Catalog_Level_WPFContainer()
        //{
        //    Database.SetInitializer(new DataInitialization());
        //}

        public Catalog_Level_WPFContainer()
            : base("name=Catalog_Level_WPFContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aggregates> Aggregates { get; set; }
        public virtual DbSet<Catalog_level> Catalog_level { get; set; }
        public virtual DbSet<Catalogs> Catalogs { get; set; }
        public virtual DbSet<Models> Models { get; set; }

    }
}
